export const mockBooks = [
    {
        id: 1,
        cover_img: "https://covers.openlibrary.org/b/id/8798095-L.jpg",
        title: "On Grand Strategy",
        author: "John Lewis Gaddis",
        description: "A profound exploration of leadership and strategic thinking through historical lenses.",
        rating: 4.5,
        genre: "History",
    },
    {
        id: 2,
        cover_img: "https://covers.openlibrary.org/b/id/10515327-L.jpg",
        title: "The Art of War",
        author: "Sun Tzu",
        description: "Ancient military treatise on tactics and strategy, still relevant today.",
        rating: 4.7,
        genre: "Philosophy",
    },
    {
        id: 3,
        cover_img: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        description: "A deep dive into the dual systems of the human mind and decision making.",
        rating: 4.6,
        genre: "Psychology",
    },
    {
        id: 4,
        cover_img: "https://covers.openlibrary.org/b/id/10958393-L.jpg",
        title: "Sapiens",
        author: "Yuval Noah Harari",
        description: "A brief history of humankind, exploring culture, science, and civilization.",
        rating: 4.8,
        genre: "Anthropology",
    },
    {
        id: 5,
        cover_img: "https://covers.openlibrary.org/b/id/10416442-L.jpg",
        title: "Deep Work",
        author: "Cal Newport",
        description: "Practical strategies for focused success in a distracted world.",
        rating: 4.4,
        genre: "Self-help",
    },
    {
        id: 6,
        cover_img: "https://covers.openlibrary.org/b/id/8235041-L.jpg",
        title: "Dune",
        author: "Frank Herbert",
        description: "A sci-fi epic of politics, religion, and power on the desert planet of Arrakis.",
        rating: 4.6,
        genre: "Science Fiction",
    },
    {
        id: 7,
        cover_img: "https://covers.openlibrary.org/b/id/9285054-L.jpg",
        title: "1984",
        author: "George Orwell",
        description: "A dystopian novel warning against totalitarianism and surveillance.",
        rating: 4.8,
        genre: "Fiction",
    },
    {
        id: 8,
        cover_img: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        description: "A powerful novel on racial injustice and moral growth in the American South.",
        rating: 4.9,
        genre: "Fiction",
    },
    {
        id: 9,
        cover_img: "https://covers.openlibrary.org/b/id/10250863-L.jpg",
        title: "Educated",
        author: "Tara Westover",
        description: "A memoir of a woman who escapes a survivalist upbringing to seek education.",
        rating: 4.7,
        genre: "Biography",
    },
    {
        id: 10,
        cover_img: "https://covers.openlibrary.org/b/id/8155080-L.jpg",
        title: "Atomic Habits",
        author: "James Clear",
        description: "An actionable guide to building good habits and breaking bad ones.",
        rating: 4.8,
        genre: "Self-help",
    },
    {
        id: 11,
        cover_img: "https://covers.openlibrary.org/b/id/10445192-L.jpg",
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        description: "A fantasy adventure that sets the stage for the epic Lord of the Rings trilogy.",
        rating: 4.9,
        genre: "Fantasy",
    },
    {
        id: 12,
        cover_img: "https://covers.openlibrary.org/b/id/10978858-L.jpg",
        title: "Becoming",
        author: "Michelle Obama",
        description: "An intimate memoir by the former First Lady of the United States.",
        rating: 4.6,
        genre: "Biography",
    },
    {
        id: 13,
        cover_img: "https://covers.openlibrary.org/b/id/11154858-L.jpg",
        title: "The Martian",
        author: "Andy Weir",
        description: "A stranded astronaut uses science and wit to survive on Mars.",
        rating: 4.7,
        genre: "Science Fiction",
    },
    {
        id: 14,
        cover_img: "https://covers.openlibrary.org/b/id/10038382-L.jpg",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        description: "A tragic tale of love, ambition, and the American dream in the Jazz Age.",
        rating: 4.5,
        genre: "Classic",
    },
    {
        id: 15,
        cover_img: "https://covers.openlibrary.org/b/id/10860972-L.jpg",
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        description: "A blunt, humorous approach to living a meaningful life.",
        rating: 4.3,
        genre: "Self-help",
    },
    {
        id: 16,
        cover_img: "https://covers.openlibrary.org/b/id/8706873-L.jpg",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        description: "A classic romantic novel exploring manners, marriage, and morality.",
        rating: 4.6,
        genre: "Romance",
    },
    {
        id: 17,
        cover_img: "https://covers.openlibrary.org/b/id/11106050-L.jpg",
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        description: "A popular science book explaining complex theories of time and space.",
        rating: 4.4,
        genre: "Science",
    },
    {
        id: 18,
        cover_img: "https://covers.openlibrary.org/b/id/8154206-L.jpg",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        description: "A story of teenage angst and alienation in post-war America.",
        rating: 4.2,
        genre: "Fiction",
    },
    {
        id: 19,
        cover_img: "https://covers.openlibrary.org/b/id/10984145-L.jpg",
        title: "The Alchemist",
        author: "Paulo Coelho",
        description: "A spiritual fable about following your dreams and listening to your heart.",
        rating: 4.5,
        genre: "Fiction",
    },
    {
        id: 20,
        cover_img: "https://covers.openlibrary.org/b/id/10512907-L.jpg",
        title: "Brave New World",
        author: "Aldous Huxley",
        description: "A dystopian classic envisioning a future shaped by technological control and conformity.",
        rating: 4.6,
        genre: "Science Fiction",
    },
];
